---

- name: Obtain SSO token
  ovirt_auth:
    url: "https://{{rhvmurl}}/ovirt-engine/api"
    username: admin@internal
    insecure: yes
    password: "{{rhvmpassword}}"
  delegate_to: localhost

- name: Virtual Machine {{ vmpower }} 
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: "{{vmpower}}"
    name: "{{ inventory_hostname }}"
  delegate_to: localhost

